apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  template:
    spec:
      lol:
        BASE: true-this-is-prod
      containers:
        - image: registry/container:latest
          name: JEGERDEV
